config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  get 'profile', to: 'users#show'
  get 'help', to: 'static_pages#help'
  root "static_pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
        #  :confirmable, :lockable, :trackable,
         :omniauthable, omniauth_providers: [:google_oauth2]
  
  enum role: [:renter, :lessor]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < ApplicationController
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
    else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
    end
  end

  def failure 
    redirect_to new_user_registration_url
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :role])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :address, :phone_number])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    root_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_alerts.html.erb
<% if notice %>
  <div class="alert alert-info mb-0" id='success-alert'><%= notice %></div>
<% elsif alert %>
  <div class="alert alert-danger mb-0" id='success-alert'><%= alert %></div>
<% end %>

<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

<script>
  $(document).ready(function() {
    $("#success-alert").fadeTo(2000, 500).slideUp(500, function() {
      $("#success-alert").slideUp(500);
    });
  });
</script>

app/views/layouts/_footer.html.erb
<nav class="navbar border-top navbar-light bg-light">
  <div class='container'>
    <ul class="nav">
      <li class="nav-item"><p>© 2021 Company, Inc</p></li>
    </ul>

    <ul class="nav">
      <a href="/">
        <%= image_tag "logo.png", style: "height: 100px" %>
      </a>
    </ul>

    <ul class="nav">
      <li class="nav-item"><a href="#" class="nav-link link-dark px-2 bi bi-envelope"> rent.bike@gmail.com</a></li>
    </ul>
  </div>
</nav>

app/views/layouts/_header.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
<nav class="py-2 bg-light fixed-top border-bottom">
  <div class="container d-flex flex-wrap">
    <ul class="nav me-auto">
      <li class="nav-item">
        <%= link_to ' Home', root_path, class: "nav-link link-dark px-2 active bi bi-house-door" %>
      </li>
      <li class="nav-item"><a href="#" class="nav-link link-dark px-2 bi bi-messenger"> Facebook</a></li>
      <li class="nav-item">
        <%= link_to ' Guide', help_path, class: "nav-link link-dark px-2 bi bi-info-circle" %>
      </li>
      <li class="nav-item">
          <a href="#" class="nav-link link-dark px-2 bi bi-phone-vibrate"> 0808083508</a>
      </li>
    </ul>
    <ul class="nav">
      <%= render 'user/session' %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentBikeWithGem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <header>  
      <%= render 'layouts/header' %>
    </header>
    <main class='mt-5 pt-2'>
      <%= render 'layouts/alerts' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </main>
  </body>
</html>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

<div class="alert alert-success" id='success-alert' role="alert">
  A simple success alert—check it out!
</div>
<button type="button" class="btn btn-primary" id="myWish">Show live alert</button>

<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

<script>
  $(document).ready(function() {
    $("#success-alert").hide();
    $("#myWish").click(function showAlert() {
      $("#success-alert").fadeTo(2000, 500).slideUp(500, function() {
        $("#success-alert").slideUp(500);
      });
    });
  });



  $(document).ready(function() {
    $("#myModal").fadeTo(2000, 500).slideUp(500, function() {
      $("#myModal").slideUp(500);
    });
  });

</script>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" id='asdsad'>
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade mt-5" id="myModal" aria-hidden="true" data-bs-focus='false' tabindex="-1" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog modal-lg bg-danger">
    <div class="modal-content">
      <div class="modal-body">
        ...aaaaaaaaaaaaaaaaaa
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<header class='py-2'>
  <div class="container d-flex flex-wrap justify-content-center align-items-center">
    <a href="/" class="d-flex align-items-center mb-3 mb-lg-0 me-lg-auto text-dark text-decoration-none">
      <%= image_tag "logo.png", class: "w-50" %>
    </a>
    <div class="col-12 col-lg-auto mb-3 mb-lg-0">
      <%= image_tag "paypal.png", style: "height: 40px" %>
    </div>
  </div>
</header>

<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
    <%= image_tag "motor.jpg", class: "d-block w-100", style: "max-height: 810px" %>    
      <div class="carousel-caption d-none d-md-block">
        <h1>Do you want to rent a car to someone else?</h1>
        <h4>Become our partner for a chance to earn extra monthly income.</h4>
        <p>
          <%= link_to 'Guide!', help_path + "?role=lessor", class: "btn btn-lg btn-primary" %>
          <%= link_to 'Lessor Register!', new_user_registration_path + '?role=lessor', class: "btn btn-lg btn-success" %>
        </p>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag "motor1.jpg", class: "d-block w-100", style: "max-height: 810px" %>
      <div class="carousel-caption d-none d-md-block">
      <h1>Let rent a car from us!</h1>
      <h4>For safe rides with quality cars.</h4>
      <p>
        <%= link_to 'Guide!', help_path + "?role=renter", class: "btn btn-lg btn-primary" %>
        <%= link_to 'Renter Register!', new_user_registration_path + '?role=renter', class: "btn btn-lg btn-success" %>
      </p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<div class="container marketing mt-4">
  <div class="row">
    <h4><i class="bi bi-star-fill"></i> CATEGORY VEHICLES ON THE PAGE</h4>
    <div class="col-lg-4">
      <div class="row justify-content-center">
        <%= image_tag "xe_so.jpg", class: "bd-placeholder-img h-100", style: "max-height: 280px" %>
      </div>
      <h2 class='text-center'>Number Bike</h2>
      <p>Some representative placeholder content for the three columns of text below the carousel. This is the first column.</p>
    </div>
    <div class="col-lg-4">
      <div class="row justify-content-center">
        <%= image_tag "xe_ga.jpg", class: "bd-placeholder-img h-100", style: "max-height: 280px" %>
      </div>
      <h2 class='text-center'>Motor Bike</h2>
      <p>Another exciting bit of representative placeholder content. This time, we have moved on to the second column.</p>
    </div>
    <div class="col-lg-4">
      <div class="row justify-content-center">
        <%= image_tag "xe_con.jpg", class: "bd-placeholder-img h-100", style: "min-height: 280px" %>
      </div>
      <h2 class='text-center'>Clutch Bike</h2>
      <p>And lastly this, the third column of representative placeholder content.</p>
    </div>
  </div>
  <h4><i class="bi bi-star-fill"></i> SALIENT FEATURES</h4>
  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading">Simple car rental procedure.</span></h2>
      <p class="lead">Another featurette? Of course. More placeholder content here to give you an idea of how this layout would work with some actual real-world content in place.</p>
    </div>
    <div class="col-md-5 d-flex justify-content-end">
      <%= image_tag "thu_tuc.jpg" %>
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7 order-md-2">
      <h2 class="featurette-heading">Drive safe with insurance</h2>
      <p class="lead">Another featurette? Of course. More placeholder content here to give you an idea of how this layout would work with some actual real-world content in place.</p>
    </div>
    <div class="col-md-5 order-md-1">
    <%= image_tag "thu_tuc5.jpg" %>
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading">Easy payment</span></h2>
      <p class="lead">And yes, this is the last block of representative placeholder content. Again, not really intended to be actually read, simply here to give you a better view of what this would look like with some actual content. Your content.</p>
    </div>
    <div class="col-md-5 d-flex justify-content-end">
      <%= image_tag "thu_tuc2.jpg" %>
    </div>
  </div>
</div>

<div class="container">
  <h4><i class="bi bi-star-fill"></i> NEWEST VIHICLES ON THE PAGE</h4>

</div>

app/views/user/_session.html.erb
<% if current_user %>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle link-dark" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Account
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
      <li><%= link_to "Profile", '#', class: "dropdown-item" %></li>
      <li><%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %></li>
      <li><hr class="dropdown-divider"></li>
      <li><%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "dropdown-item" %></li>
    </ul>
  </li>
<% else %>
  <li class="nav-item">
    <%= link_to ' Login', new_user_session_path, class: "nav-link link-dark px-2 bi bi-box-arrow-in-right" %>
  </li>
<% end %>

app/views/users/show.html.erb
<%= link_to ' update', edit_user_registration_path, class: "nav-link link-dark px-2 active bi bi-house-door" %>
<%= link_to ' unlock', new_user_unlock_path, class: "nav-link link-dark px-2 active bi bi-house-door" %>
<%= current_user.sign_in_count %> <br>
<%= current_user.current_sign_in_at %><br>
<%= current_user.last_sign_in_at %><br>
<%= current_user.current_sign_in_ip %><br>
<%= current_user.last_sign_in_ip %>